# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: mvn --batch-mode clean install -DskipTests=true

      - name: Upload Connector
        uses: actions/upload-artifact@v4
        with:
          name: FreeIPA Connector
          path: target/connector-freeipa-*.jar
          if-no-files-found: error

      - name: Create Release
        run: |-
          gh release create ${GIT_TAG} \
            --title "Release ${GIT_TAG}" \
            --generate-notes \
            target/connector-freeipa-*.jar
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_TAG: ${{ github.ref_name }} # https://docs.github.com/en/actions/reference/workflows-and-actions/variables
